[technote]
id = "RTN-106"
series_id = "RTN"
canonical_url = "https://rtn-106.lsst.io"
github_url = "https://github.com/lsst/rtn-106"
github_default_branch = "main"
date_created = 2025-08-26T01:11:01Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Leanne P."
name.family = "Guy"
internal_id = "guylp"
orcid = "https://orcid.org/0000-0003-0800-8755"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
address = "La Serena"
